In [15]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

vertically_stacked = np.vstack((A, B))
print("Vertically Stacked:\n", vertically_stacked)

horizontally_stacked = np.hstack((A, B))
print("Horizontally Stacked:\n", horizontally_stacked)


Vertically Stacked:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontally Stacked:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [16]:
A_flat = A.flatten()
B_flat = B.flatten()

common_elements = np.intersect1d(A_flat, B_flat)
print("Common Elements:\n", common_elements)

Common Elements:
 []


In [17]:
min_value = 5
max_value = 10

elements_in_range = A[(A >= min_value) & (A <= max_value)]
print("Elements in range 5 to 10:\n", elements_in_range)


Elements in range 5 to 10:
 [5 6]


In [18]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print(filtered_iris)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [19]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [20]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)

df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print(df[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


<ipython-input-20-b2a8cb14c46f>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
<ipython-input-20-b2a8cb14c46f>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True

In [21]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

filtered_rows = df[df.sum(axis=1) > 100]

print(filtered_rows)

     0   1   2   3
0   37  13  26  34
1   24  29  31  30
2   28  30  14  39
6   35  19  34  29
7   39  23  34  36
10  30  30  28  33
11  32  36  32  23
